# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(700, 492)
        self.columnView = QtWidgets.QColumnView(Form)
        self.columnView.setGeometry(QtCore.QRect(10, 50, 681, 192))
        self.columnView.setObjectName("columnView")
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setGeometry(QtCore.QRect(10, 250, 681, 192))
        self.tableView.setObjectName("tableView")
        self.pshBttnQuit = QtWidgets.QPushButton(Form)
        self.pshBttnQuit.setGeometry(QtCore.QRect(600, 460, 90, 28))
        self.pshBttnQuit.setObjectName("pshBttnQuit")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 681, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblPath = QtWidgets.QLabel(self.widget)
        self.lblPath.setObjectName("lblPath")
        self.horizontalLayout.addWidget(self.lblPath)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pshBttnReadPath = QtWidgets.QPushButton(self.widget)
        self.pshBttnReadPath.setObjectName("pshBttnReadPath")
        self.horizontalLayout.addWidget(self.pshBttnReadPath)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pshBttnQuit.setText(_translate("Form", "&Quit"))
        self.lblPath.setText(_translate("Form", "Path : "))
        self.pshBttnReadPath.setText(_translate("Form", "Read Path"))
